language: python
sudo: false
python:
- '2.6'
- '2.7'
- '3.3'
- '3.4'
- '3.5'
- '3.6'
- pypy
before_install:
  - pip install coveralls
install:
- pip install -r test_requirements.txt
- pip install -e .
script:
- py.test tests --cov=pact
after_success:
- coveralls
deploy:
  provider: pypi
  user: vmalloc
  password:
    secure: Sru8c67ASNA+JRqtBtxDyQIJyRlHyNhcGdLen6HisGnh27YBmLYpgoYUem3YAwNkIneKgggnafOwhQpyVLGh6qkGtUiUJ76yN/57MrWabqq2N/xjvxpMDvCdB+Y/FeMOxkaEzzkCOauHrsUws/ePX/u65K4GgVQXZB17sDxAGwc=
  on:
    tags: true
    repo: getslash/pact
